export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '',
    headline: 'About Me',
    description1: `As an optometrist turned self-taught programmer, I am passionate about using data to drive decision making or contribute to projects that can improve people's lives.`,
    description2: `My journey began with learning how to program during COVID-19 out of curiousity. This led me to explore various programming languages and other areas of IT (cybersecurity and cloud computing) and subsequently developed a strong interest in programming and working with data.`,
    description3: `To further pursue my interests, I am currently completing a Graduate Certificate in Data Analytics at Deakin University alongside my full time work. I plan to transition from my medical field to work in the data analytics and science industry to continue my passion in this area.`, 
    description4: `My curiousity for coding has driven me to seek out new challenges and continue expanding my knowledge, subsequently leading me to a pursue a career in the IT industry.`,
    imgStart: true,
    img: require('../../images/png-1.png'),
    alt: 'portrait',
    // dark: false,
    // primary: false,
    darkText: true,
}
export const homeObjTwo = {
    id: 'skills',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine1: 'Programming Languages:',
    topLine2: 'Frameworks/Software',
    // topLineSoftware: 'Software:',
    topLine3: 'Certificates:',
    topLine4: 'Courses:',
    headline: 'Skills/Certificates',
    description1: 'Python, R, SQL, JavaScript, HTML, CSS, Shell',
    description2: 'NumPy, Pandas, scikit-learn, Matplotlib, Seaborn, PowerBI, Tabelau, React',
    // description8: 'PowerBI, Tabelau',
    description3: 'AWS Cloud Practitioner Essentials',
    description4: "IBM Cybersecurity Analyst Professional Certificate",
    description5: "Deakin: Graduate Certificate in Data Analytics (2024)",
    description6: "CS50: Introduction to Computer Science by Harvard University (2023)",
    description7: "CS50: Introduction to Programming with Python by Harvard University (2023)",
    imgStart: false,
    img: require('../../images/png-2.png'),
    alt: 'certification',
    // dark: true,
    // primary: true,
    darkText: false,
}

