export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '',
    headline: 'About Me',
    description1: `As an optometrist turned self-taught programmer, I am passionate about creating innovative software solutions that improve people's lives.`,
    description2: `My journey began with tinkering around with computers and coding in my spare time. This led me to explore programming languages and self-learn various software development skills.`,
    description3: `Through determination and hard work, I have acquired a strong foundation in coding, database design, and software development.`, 
    description4: `My enthusiasm for coding has driven me to seek out new challenges and continue expanding my knowledge base.`,
    imgStart: true,
    img: require('../../images/png-1.png'),
    alt: 'portrait',
    // dark: false,
    // primary: false,
    darkText: true,
}
export const homeObjTwo = {
    id: 'skills',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine1: 'Programming Languages:',
    topLine2: 'Frameworks/Software',
    // topLineSoftware: 'Software:',
    topLine3: 'Certificates:',
    topLine4: 'Courses:',
    headline: 'Skills/Certificates',
    description1: 'Python, R, SQL, JavaScript, HTML, CSS, Shell',
    description2: 'NumPy, Pandas, scikit-learn, Matplotlib, Seaborn, PowerBI, Tabelau, React',
    // description8: 'PowerBI, Tabelau',
    description3: 'AWS Cloud Practitioner Essentials',
    description4: "IBM Cybersecurity Analyst Professional Certificate",
    description5: "Deakin: Graduate Certificate in Data Analytics (2024)",
    description6: "CS50: Introduction to Computer Science by Harvard University (2023)",
    description7: "CS50: Introduction to Programming with Python by Harvard University (2023)",
    imgStart: false,
    img: require('../../images/png-2.png'),
    alt: 'certification',
    // dark: true,
    // primary: true,
    darkText: false,
}

